__title__ = "flowty"
__description__ = "A tool and library for computing optical flow"
__version__ = "0.0.0"
__author__ = "Will Price"
__author_email__ = "will.price94+flowty@gmail.com"
__license__ = "MIT"
__copyright__ = "Copyright 2019 Will Price"
